# Generated by Django 5.0.3 on 2024-04-14 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='номер')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher', verbose_name='Учитель')),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.AlterField(
            model_name='schoolboy',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.academicgroup'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
