# Generated by Django 5.0.3 on 2024-04-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_value',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_value',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='img',
            field=models.CharField(max_length=20, verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='title',
            field=models.CharField(max_length=20, unique=True, verbose_name='Наименование'),
        ),
    ]
