# Generated by Django 5.0.3 on 2024-04-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='img',
            field=models.CharField(default='lab_1.jpg', max_length=20),
            preserve_default=False,
        ),
    ]
